In [1]:
import numpy as np
import random
from random import randint
import pandas as pd

In [130]:
class Knapsack(object):
    def __init__(self, capacity, items):
        self.capacity = capacity
        self.items = items

In [253]:
class Individual(object):
    def __init__(self, chromosome, knapsack):
        self.chromosome = chromosome
        self.knapsack = knapsack
        self.fitness = 0
        self.fitness_func()
    
    def mutate(self):
        n = len(self.chromosome)
        for i in range(n):
            k = random.uniform(0, 1)
            if k > 0.5:
                self.chromosome[i] = int(not self.chromosome[i])

    def fitness_func(self):
        self.fitness = 0
        w = self.knapsack.items[0]
        v = self.knapsack.items[1]
        if (sum(self.chromosome*w) <= self.knapsack.capacity):
            profits = self.chromosome*v
            self.fitness = sum(profits)
    
    def crossover(self, parent2):
        threshold = random.randint(1, len(self.chromosome)-1)
        half1 = self.chromosome[threshold:]
        half2 = parent2.chromosome[threshold:]
        child1 = self.chromosome[:threshold]
        child2 = parent2.chromosome[:threshold]
        child1 = np.append(child1, half2)
        child2 = np.append(child2, half1)
        return [child1, child2]
    
    def produce_offspring(self, parent2):
        chromosome = random.choice(self.crossover(parent2))
        child = Individual(chromosome, self.knapsack)
        child.mutate()
        child.fitness_func()
        return child
        
        

In [260]:
class GA(object):
    def __init__(self, knapsack, pop_size, max_iter):
        self.knapsack = knapsack
        self.pop_size = pop_size
        self.population = self.create_initial_population()
        self.generation = 1
        self.max_iter = max_iter
    
    def create_initial_population(self):
        population = []
        for i in range(self.pop_size):
            l = len(self.knapsack.items[0])
            genotype = [np.random.randint(0, 2) for _ in range(l)]
            genome = Individual(np.array(genotype), self.knapsack)
            population.append(genome)
        return population
    
    def get_fitness_statistics(self):
        avg_fitness = 0
        all_fitness = []
        best_fitness = self.population[0].fitness
        best_genome = self.population[0].chromosome
        for genome in self.population:
            all_fitness.append(genome.fitness)
        avg_fitness = sum(all_fitness)/len(self.population)
        return [best_fitness, best_genome, avg_fitness]
    
    def select_elitism(self):
        new_generation = []
        s = int(10*len(self.population)/100)
        new_generation.extend(self.population[:s])
        # 50% fittest population will mate to produce offspring
        s = int(90*len(self.population)/100)
        for _ in range(s):
            parent1 = random.choice(self.population[:50])
            parent2 = random.choice(self.population[:50])
            child = parent1.produce_offspring(parent2)
            new_generation.append(child)
        self.population = new_generation
        
    
    def run(self):
        best_fitness = 0
        best_average_fitness = 0
        best_genome = []
        generations_without_improvement = 0
        convergence_threshold = 100
        
        for i in range(self.max_iter):
            self.population = sorted(self.population, key = lambda x:x.fitness, reverse = True)
            statistics = self.get_fitness_statistics()
            
            if statistics[0] > best_fitness:
                best_fitness = statistics[0]
                best_genome = statistics[1]
            
            self.select_elitism()
            
            if statistics[2] > best_average_fitness:
                best_average_fitness = statistics[2]
                generations_without_improvement = 0
            else:
                generations_without_improvement += 1
            
            print(self.generation, best_genome, best_fitness)
            
            if (generations_without_improvement >= convergence_threshold):
                return [best_fitness, best_genome]
            
            self.generation += 1
        return [best_fitness, best_genome]

In [262]:
w = np.array([12,  7, 11, 8, 9])
v = np.array([24, 13, 23, 15, 16])
capacity = 26
items = np.array([w, v])
ks = Knapsack(capacity, items)

ga = GA(ks, 10, 150)
w, v, ga.run() 

1 [1 0 0 0 1] 40
2 [1 0 1 0 0] 47
3 [0 1 1 1 0] 51
4 [0 1 1 1 0] 51
5 [0 1 1 1 0] 51
6 [0 1 1 1 0] 51
7 [0 1 1 1 0] 51
8 [0 1 1 1 0] 51
9 [0 1 1 1 0] 51
10 [0 1 1 1 0] 51
11 [0 1 1 1 0] 51
12 [0 1 1 1 0] 51
13 [0 1 1 1 0] 51
14 [0 1 1 1 0] 51
15 [0 1 1 1 0] 51
16 [0 1 1 1 0] 51
17 [0 1 1 1 0] 51
18 [0 1 1 1 0] 51
19 [0 1 1 1 0] 51
20 [0 1 1 1 0] 51
21 [0 1 1 1 0] 51
22 [0 1 1 1 0] 51
23 [0 1 1 1 0] 51
24 [0 1 1 1 0] 51
25 [0 1 1 1 0] 51
26 [0 1 1 1 0] 51
27 [0 1 1 1 0] 51
28 [0 1 1 1 0] 51
29 [0 1 1 1 0] 51
30 [0 1 1 1 0] 51
31 [0 1 1 1 0] 51
32 [0 1 1 1 0] 51
33 [0 1 1 1 0] 51
34 [0 1 1 1 0] 51
35 [0 1 1 1 0] 51
36 [0 1 1 1 0] 51
37 [0 1 1 1 0] 51
38 [0 1 1 1 0] 51
39 [0 1 1 1 0] 51
40 [0 1 1 1 0] 51
41 [0 1 1 1 0] 51
42 [0 1 1 1 0] 51
43 [0 1 1 1 0] 51
44 [0 1 1 1 0] 51
45 [0 1 1 1 0] 51
46 [0 1 1 1 0] 51
47 [0 1 1 1 0] 51
48 [0 1 1 1 0] 51
49 [0 1 1 1 0] 51
50 [0 1 1 1 0] 51
51 [0 1 1 1 0] 51
52 [0 1 1 1 0] 51
53 [0 1 1 1 0] 51
54 [0 1 1 1 0] 51
55 [0 1 1 1 0] 51
56 [0 1 1 1 0] 51
5

(array([12,  7, 11,  8,  9]),
 array([24, 13, 23, 15, 16]),
 [51, array([0, 1, 1, 1, 0])])

In [269]:
# generate n random items
items = []
n = 10
w = np.random.randint(1, 10, n)
v = np.random.randint(1, 10, n)
items = np.array([w, v])
# maximum weights of the knapsack
capacity = 40
ks = Knapsack(capacity, items)

ga = GA(ks, 10, 150)
w, v, ga.run(), capacity - sum(w*ga.run()[1]) 

1 [0 1 0 0 1 1 1 1 1 0] 30
2 [1 1 0 0 1 0 1 1 1 0] 36
3 [1 1 0 0 1 0 1 1 1 0] 36
4 [1 1 0 0 1 0 1 1 1 0] 36
5 [1 1 0 0 1 0 1 1 1 0] 36
6 [1 1 0 0 1 0 1 1 1 0] 36
7 [1 1 0 0 1 0 1 1 1 0] 36
8 [1 1 0 0 1 0 1 1 1 0] 36
9 [1 1 0 0 1 0 1 1 1 0] 36
10 [1 1 0 0 1 0 1 1 1 0] 36
11 [1 1 0 0 1 0 1 1 1 0] 36
12 [1 1 0 0 1 0 1 1 1 0] 36
13 [1 1 0 0 1 0 1 1 1 0] 36
14 [1 1 0 0 1 0 1 1 1 0] 36
15 [1 1 0 0 1 0 1 1 1 0] 36
16 [1 1 0 0 1 0 1 1 1 0] 36
17 [1 1 0 0 1 0 1 1 1 0] 36
18 [1 1 0 0 1 0 1 1 1 0] 36
19 [1 1 0 0 1 0 1 1 1 0] 36
20 [1 1 0 0 1 0 1 1 1 0] 36
21 [1 1 0 0 1 0 1 1 1 0] 36
22 [1 1 0 0 1 0 1 1 1 0] 36
23 [1 1 0 0 1 0 1 1 1 0] 36
24 [1 1 0 0 1 0 1 1 1 0] 36
25 [1 1 0 0 1 0 1 1 1 0] 36
26 [1 1 0 0 1 0 1 1 1 0] 36
27 [1 1 0 0 1 0 1 1 1 0] 36
28 [1 1 0 0 1 0 1 1 1 0] 36
29 [1 1 0 0 1 0 1 1 1 0] 36
30 [1 1 0 0 1 0 1 1 1 0] 36
31 [1 1 0 0 1 0 1 1 1 0] 36
32 [1 1 0 0 1 0 1 1 1 0] 36
33 [1 1 0 0 1 0 1 1 1 0] 36
34 [1 1 0 0 1 0 1 1 1 0] 36
35 [1 1 0 0 1 0 1 1 1 0] 36
36 [1 1 0 0 1 0 1 1 1 0] 36
3

(array([8, 3, 6, 7, 6, 8, 4, 9, 5, 9]),
 array([8, 3, 1, 3, 4, 2, 8, 7, 6, 2]),
 [36, array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0])],
 5)